name: Flutter Action

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: drawing_app
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter build appbundle
  
  analyze:
    name: Static Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: drawing_app
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter analyze
          
  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: drawing_app
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter test --verbose --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
